spring:
  application:
    name: gateway-service-zuul

server:
  port: 8888


  
zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/
    hello:
      path: /hello/**
      url: http://localhost:9000/
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
