spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
      
server:
  port: 8888


  
zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/
    hello:
      path: /hello/**
      url: http://localhost:9000/
  retryable: true
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
      
ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0